# Prison Escape Plugin Configuration
# 语言 (Language)
language: Chinese

# 世界黑名单 (World Blacklist)
worldBlackList: []

# 逃离时间 (Escape Time)
escapeTime: 15

# 默认囚犯人数 (Default Prisoner Count)
playerNum: 2

# 默认监狱赌注 (Default Prison Wager)
counter: 10.00
